### ISSUE TITLE
Add Modifier to Liquibase Properties File for KeePass Subpath

### ISSUE THREAD

**Issue by jlpdeveloper** [jlpdeveloper/liquibase-security#3]
## Overview

`v1.0.0` limits the ability to use multiple servers with its KeePass path. There needs to be a way of adding a path modifier to the liquibase properties file that will extend the default `Liquibase/Environments` path with a sub path to allow for multiple servers

## Todo
- [ ] Move code that checks if `liquibase.properties` exists
- [ ] Write code to check the `liquibase.properties` file for a `liquibase.secret-subpath` value
- [ ] If that value exists, then append it to the KeePass path before trying to query. It should also clean up trailing `/`s
